### ISSUE TITLE
nothing happened in my winphone 8

### ISSUE THREAD

**Issue by bau720123** [kolwit/com.kolwit.updatelivetile#1]
these are all my code

```
var tileOptions = 
{
tileType: 'standard',
Title: 'Hello',
Count: 'Count',
BackgroundColor: '#11BB75' // color hex like in CSS
};

var successFunc = function () { alert("success"); };
var errorFunc = function (c,m) { alert('Tile update failed: ' + c + ' - ' + m); };

window.plugins.UpdateLiveTile.updateTile(successFunc, errorFunc, tileOptions);
```

when I execute it by PGB 3.5，but nothing happened or change in my winphones's LiveTile

**Comment by kolwit** [comment]
Hi @bau720123 ,

Can you try to but in a numeric value between 0 and 99 in the count value. It should however be passed as a string. 
Also, to be able to use BackgroundColor you should take the iconic tileType. In case another tyleType is selected the value should be ignored.

In some cases i experienced while testing that the tile did not update the success function was triggered but the tile did not update. After removing the tile from the screen and readding it it did pop up.

In the function try something like this:

```
var tileOptions = {
        tileType:                   'iconic',
        Title:                      'Hello',
        WideContent1:               'your WideContent1',
        Count:                      '25', // numeric value from 0 to 99
        BackgroundColor:            '#11BB75' // color hex like in CSS
    };

var successFunc = function () { alert("success"); };
var errorFunc = function (c,m) { alert('Tile update failed: ' + c + ' - ' + m); };

window.plugins.UpdateLiveTile.updateTile(successFunc, errorFunc, tileOptions);
```

Did the success or error function trigger? Did you get an alert?

**Comment by bau720123** [comment]
hi @kolwit 
I use your code completely
but still same situation
no alert message can be trigger
I really check for many times...

**Comment by kolwit** [comment]
Hi @bau720123 ,

Ok,
i just went checking the code i use myself.
I figure now that i did update the Count value to an integer.

So Count should be fully numeric, for example

```
Count: 25,
```

otherwise maybe start with the default tile, the flip tile i also tested a lot:

```
var tileOptions = {
        tileType:                   'standard',
        Title:                      'Hello',
        BackTitle:                      'BackHello',
        BackContent:               'your BackContent text',
        Count:                      25
    };

var successFunc = function () { alert("success"); };
var errorFunc = function (c,m) { alert('Tile update failed: ' + c + ' - ' + m); };

document.addEventListener("deviceready", function() {
        window.plugins.UpdateLiveTile.updateTile(successFunc, errorFunc, tileOptions);
        }, false);
```

added note: i added now the deviceready event listener around the plugin trigger, just to make sure it is executed after everything is loaded.

**Comment by bau720123** [comment]
hi @kolwit 
still no any alert message trigger
have you use the code in PGB too ?
